name: Build and Push Docker Image to GHCR

# Define permissões para o GITHUB_TOKEN
permissions:
  contents: read  # Permissão para ler o conteúdo do repositório
  packages: write  # Permissão para empurrar pacotes no GHCR

on:
  push:
    branches:
      - main  # ou qualquer outra branch que você deseje
  # pull_request:
  #   branches:
  #     - main  # ou qualquer outra branch que você deseje

jobs:
  build:
    runs-on: ubuntu-latest  # Ambiente onde o GitHub Actions vai rodar o job
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Faz o checkout do código do repositório para o runner

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Configura o Docker Buildx, necessário para o GitHub Actions

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/my-docker-image:latest .  

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2  # Faz login no GHCR
      with:
        registry: ghcr.io
        username: ${{ github.actor }}  # O nome do usuário do GitHub
        password: ${{ secrets.GITHUB_TOKEN }}  # Token de autenticação do GitHub, gerado automaticamente

    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/${{ github.repository }}/my-docker-image:latest  # Envia a imagem para o GHCR
